### ISSUE TITLE
Simplecov doesnt work with Knapsack Pro 7.4 and minitest

### ISSUE THREAD

**Issue by rafaeelaudibert** [KnapsackPro/knapsack_pro-ruby#257] opened 2024-05-24 19:04 UTC
Hey!

I've been trying to update our Knapsack pro gem from version 6.0 to 7.4 but Im having problems with our minitest tests. We use `SimpleCov` alongside KnapsackPro but the output files are not being generated. There's no `coverage` folder anywhere after running the tests.

This did work with Knapsack 6.0.

It's worth noticing that minitest is properly generating its XML output, and we're merging them as we did before. The only change is that simplecov is not generating output anymore. I've confirmed Simplecov is being properly initialized, and we have the following snippet in place - we had it in place with 6.0 as well.

```ruby
KnapsackPro::Hooks::Queue.before_queue do |_queue_id|
  SimpleCov.command_name("api_ci_node_#{KnapsackPro::Config::Env.ci_node_index}")
end
```

Any idea on what could be causing this?

**Comment by 3v0k4** [comment] 2024-05-27 09:56
Hey, @rafaeelaudibert. I'm looking into it and will get back to you soon.

**Comment by ArturT** [comment] 2024-06-03 08:34
@rafaeelaudibert Do you use other queue hooks than `KnapsackPro::Hooks::Queue.before_queue`?

The only change for Minitest was a fix in [6.0.4](https://github.com/KnapsackPro/knapsack_pro-ruby/blob/master/CHANGELOG.md#604).

The 7.x release does not introduce changes to Minitest.

Could you answer Riccardo's questions? That would help us narrow down the root issue. Thank you.

**Comment by connorshea** [comment] 2024-06-03 18:13
`at_exit` is what emits the coverage (https://github.com/simplecov-ruby/simplecov?tab=readme-ov-file#customizing-exit-behaviour), would that have anything to do with the problem, if it's being removed?

I'm having some problems getting simplecov to work on my setup, but I've only tried 7.5.1 and haven't gotten simplecov to work with Knapsack thus far. I tried downgrading to 6.0.3 to see if that changed anything, but that caused it to fail with a VCR/WebMock-related error. I can provide more information once I dig into the problem a bit further.

**Comment by connorshea** [comment] 2024-06-03 19:27
Out of curiosity, does it matter if `simplecov` is `require`d before `knapsack_pro`?

**Comment by connorshea** [comment] 2024-06-03 19:49
**Are there any other code changes besides updating the knapsack_pro version?**
Nope, 6.0.3 works and 7.5.1 doesn't.

**Does the test suite run rm -rf coverage or anything similar as part of running the tests? Maybe in a hook?**
Nope

**Do you see the Coverage report generated for ... line in your CI node terminal output?**
Nope

**Does Simplecov generate the report when you call Minitest directly (without Knapsack Pro)?**
Yep

**Does running Knapsack Pro with [KNAPSACK_PRO_LOG_LEVEL=debug](https://docs.knapsackpro.com/ruby/reference/#knapsack_pro_log_level) log anything meaningful?**
I will try this next, but I assume it won't.

**Could you try to identify which specific version of Knapsack Pro in between 6.0.0 and 7.4.0 breaks Simplecov for you?**
It definitely appears to be 6.0.4 that breaks the coverage output. I'll try 6.0.4 itself to make sure that's the first version with the problem, though.

**Comment by connorshea** [comment] 2024-06-03 20:14
On 7.5.1, if I add this to my test_helper.rb file, I get coverage reports again:

```rb
KnapsackPro::Hooks::Queue.after_queue do
  SimpleCov.result.format!
end
```

Although I think it may also be getting stuck on that last job like it was before 6.0.4 :(

**Comment by connorshea** [comment] 2024-06-04 18:10
The issue mentioned above seems to have something to do with the last job/jobs taking a lot longer than the other ones. Something about the logic for the queue mode seems to break or trigger a race condition when there's still one more job running tests while all the others have completed. At least, that seems to be the cause. And it's the only one I've come up with that really makes sense, given that the issue is inconsistent.

Unfortunately, I don't have much to offer beyond that.

**Comment by ArturT** [comment] 2024-06-04 22:22
Thanks @connorshea for detailed research. This is helpful.


> On 7.5.1, if I add this to my test_helper.rb file, I get coverage reports again:
> 
> ```ruby
> KnapsackPro::Hooks::Queue.after_queue do
>   SimpleCov.result.format!
> end
> ```
> 
> I _think_ this fully fixes both the coverage report not generating _and_ the problem that was fixed by 6.0.4?

It seems reasonable. Good findings.

> EDIT: Sometimes the tests seem to get stuck at the very end of the process. I'm not sure why.
> 
> We have 20 parallel jobs, 18 or 19 of them all finish within a few seconds of each other, and then sometimes the last 1 or 2 just get stuck. Other times they all pass fine at around the exact same time, and nothing gets stuck.

You can debug the free with the following instructions:
https://docs.knapsackpro.com/ruby/troubleshooting/#knapsack-pro-hangs

Add the following script to test_helper.rb. Thanks to that, you will see the backtrace showing what code line causes the hanging problem. Backtrace is visible only if the Ruby process got kill with USR1 signal. Learn more from this [GitHub issue](https://github.com/rspec/rspec-rails/issues/1353#issuecomment-93173691).

```ruby
# source https://github.com/rspec/rspec-rails/issues/1353#issuecomment-93173691
puts "Process pid: #{Process.pid}"

trap 'USR1' do
  threads = Thread.list

  puts
  puts "=" * 80
  puts "Received USR1 signal; printing all #{threads.count} thread backtraces."

  threads.each do |thr|
    description = thr == Thread.main ? "Main thread" : thr.inspect
    puts
    puts "#{description} backtrace: "
    puts thr.backtrace.join("\n")
  end

  puts "=" * 80
end
```

If the CI provider does not kill the frozen process, you can do it by running the below command in the terminal (when you are ssh-ed into the CI node):

```bash
kill -USR1 <process pid>
```

Alternatively, you can use the timeout program to send the USR1 signal after Knapsack runs too long.

```bash
timeout --signal=USR1 600 bundle exec rake "knapsack_pro:queue:rspec[--format d]"
```

Notice that 600 is in seconds. It sends the signal after 10 minutes of running the command. You may want to adjust that number to ensure the USR1 signal is sent after the process is stuck and not before.

**Comment by ArturT** [comment] 2024-06-04 22:25
@rafaeelaudibert Does adding the following help in your case?

```ruby
KnapsackPro::Hooks::Queue.after_queue do
  SimpleCov.result.format!
end
```

**Comment by ArturT** [comment] 2024-06-05 20:20
I've updated the changelog for the 6.0.4 version to cover breaking changes affecting simplecov users.
https://github.com/KnapsackPro/knapsack_pro-ruby/blob/update-changelog-simplecov/CHANGELOG.md

I also updated our simplecov docs:
https://docs.knapsackpro.com/ruby/simplecov/

and CodeClimate + simplecov docs:
https://docs.knapsackpro.com/ruby/code-climate/

**Comment by connorshea** [comment] 2024-06-06 16:21
> I've updated the changelog for the 6.0.4 version to cover breaking changes affecting simplecov users. https://github.com/KnapsackPro/knapsack_pro-ruby/blob/update-changelog-simplecov/CHANGELOG.md
> 
> I also updated our simplecov docs: https://docs.knapsackpro.com/ruby/simplecov/
> 
> and CodeClimate + simplecov docs: https://docs.knapsackpro.com/ruby/code-climate/

That first link is broken now since the branch was merged

> @connorshea I think the issue with hanging tests is unrelated to the original simplecov issue.
> 
> We could keep working on resolving hanging tests in the private support email thread that's been going on.
> 
> I propose we close this GitHub issue as the original problem is solved.

That's fair! I'm fine with us closing this one unless Rafael needs any further help.

**Comment by connorshea** [comment] 2024-06-06 16:23
I'll try the debugging steps you mentioned a bit later, I think switching to Regular Mode and forgoing code coverage has solved the issue we were having for now, regardless.

**Comment by ArturT** [comment] 2024-06-07 12:58
> That first link is broken now since the branch was merged

@connorshea Good catch! 

I've updated [my comment](https://github.com/KnapsackPro/knapsack_pro-ruby/issues/257#issuecomment-2150898662) and [the link](https://github.com/KnapsackPro/knapsack_pro-ruby/blob/master/CHANGELOG.md#604).

**Closed** 2024-06-07 12:59 UTC
Labels: bug
